[package]
name = "quantiles"
version = "0.3.1"
authors = ["Brian L. Troutwine <blt@postmates.com>"]
build = "build.rs"

description = "a collection of approximate quantile algorithms"
repository = "https://github.com/postmates/quantiles"

readme = "README.md"
license = "MIT"

keywords = ["statistics", "histogram", "quantiles", "percentiles", "approximation"]

[profile.release]
lto = true

[dev-dependencies]
quickcheck = "0.3"

[dependencies]
serde = "0.8"

[build-dependencies]
serde_codegen = "0.8"
